# Generated by Django 2.1.3 on 2018-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
