# Generated by Django 2.1.3 on 2018-11-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sizes',
            field=models.TextField(default=''),
        ),
    ]
