# Generated by Django 2.1.3 on 2018-12-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_post2_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='link',
        ),
    ]
