# Generated by Django 2.1.3 on 2018-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_remove_post2_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='link',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
